In [1]:
import numpy as np
List = [True, "2", 3.0, 4]

print([type(item) for item in List])

[<class 'bool'>, <class 'str'>, <class 'float'>, <class 'int'>]


In [2]:
array_int = np.array([1, 4, 2, 5, 3])

print("Array:", array_int)
print("Type:", array_int.dtype)

Array: [1 4 2 5 3]
Type: int64


In [3]:
array_mixed = np.array([3.14, 4, 2, 3])

print("Mixed Array:", array_mixed)
print("Type:", array_mixed.dtype)

Mixed Array: [3.14 4.   2.   3.  ]
Type: float64


In [4]:
List = list(range(10))
List

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:

type(List[0])

int

In [6]:
L2 = [str(c) for c in List]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

In [8]:
L3st = [True, "2", 3.0, 4]
[type(item) for item in L3st]

[bool, str, float, int]

In [9]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
import numpy as np

In [11]:
# creating an int array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [13]:
np.array([3.14, 4, 2, 3]).dtype

dtype('float64')

In [14]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [15]:
# nested lists in numpy array 
np.array([range(i, i+3) for i in [2,4,6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [16]:
# creating length 10 integer array of zeroes
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# create a 3X5 floating-point array filled withones
np.ones((3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.full((3,3), 3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [19]:
# creating an array of linear sequence
np.arange(0, 20, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [26]:
np.random.random((3, 3))

array([[0.11710959, 0.89230812, 0.69017916],
       [0.25994421, 0.29858944, 0.29139737],
       [0.97962072, 0.78382081, 0.38231377]])

In [27]:
# Creating a 3x3 array of normally distributed random values with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-0.58655927, -0.05796233,  2.04845623],
       [ 0.91833942, -0.66366778, -0.32424113],
       [-1.26434604,  0.99780814, -1.69328084]])

In [29]:
# Creat a 3x3 array of random integers in the interval.
np.random.randint(0, 10, (3, 3)) 

array([[7, 3, 6],
       [5, 4, 6],
       [0, 6, 0]], dtype=int32)

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.empty(3)

array([1., 1., 1.])